name: CI

on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.13.0

      - name: Fmt
        run: zig fmt . --check
        if: matrix.os == 'ubuntu-latest'

      - name: Build
        run: zig build

      - name: Build release
        run: zig build -Doptimize=ReleaseSafe
